name: SREGS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ffmpeg=4.2.2
  - pillow=10.2.0
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.8.1
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - typing_extensions=4.9.0
  - tqdm
  - pip:
    - submodules/diff-surfel-rasterization
    - submodules/simple-knn
    - matplotlib==3.5.3
    - torchmetrics==1.2.0
    - timm==0.9.12
    - opencv_python==4.8.1.78
    - imageio==2.31.2
    - open3d==0.17.0
    - mediapy==1.1.2
    - lpips==0.1.4
    - scikit-image==0.21.0
    - trimesh==4.3.2
